---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-15.04
  # - name: centos-6.4

suites:
  - name: issues/10
    run_list:
      - recipe[test::issue_10]
    attributes:
